# CONFIGURACIÓN PARA RENDER (POSTGRESQL)

# 1. Forzamos el uso del Driver de PostgreSQL (Esto evita el error de MySQL)
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Construimos la URL usando la variable de Render
spring.datasource.url=jdbc:${SPRING_DATASOURCE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# 3. Dialecto de base de datos para PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# 4. Puerto que Render nos asigna
server.port=${PORT:8080}